### ISSUE TITLE
Add screenshots for display on WP.org

### ISSUE THREAD

**Issue by tevyaw** [WordXpress/Latter-day_Linker#10]
Include attached. I ended up just doing my own so I could remove that setting and a few other things. Yours were nice @hiren1612  but I also like to do enlarged versions so they're easy to see on HiDPI screens.
[screenshots.zip](https://github.com/WordXpress/Latter-day_Linker/files/3480047/screenshots.zip)

**Comment by hiren1612** [comment]
It's looking better.
